---
- name: Checking if directory exists
  stat:
    path: "{{ item }}"
    follow: true
  with_items: "{{ include_vars.paths }}"
  register: include_vars_dir
  loop_control:
    label: "{{ item }}"

- name: "Include all {{ include_vars.extensions | map('regex_replace', '(.*)', '*.\\1') | join(',') }} files"
  include_vars:
    dir: "{{ item.item }}"
    depth: "{{ include_vars.depth }}"
    extensions: "{{ include_vars.extensions }}"
    ignore_files: "{{ include_vars.excludes }}"
  with_items: "{{ include_vars_dir.results }}"
  when: item.stat.exists
  register: included
  loop_control:
    label: "{{ item.item }}"

#- name: Included the following files
#  debug:
#    msg: "{{ included.results.0.ansible_included_var_files }}"
