---
- name: Update pip (and fix potential pip errors)
  become: true
  shell: python -m pip install --upgrade --force pip

- name: Run pip to install dependencies
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - "jmespath"